### ISSUE TITLE
cursor: no tools, prompts or resources.

### ISSUE THREAD

**Issue by emeagenciadigital** [ChromeDevTools/chrome-devtools-mcp#111]
Installed the mcp server thorugh cursor install mcp button and is not able to connect to it. 

How to debug this? All other mcp server works and im currently running on node 22.19.0

<img width="408" height="135" alt="Image" src="https://github.com/user-attachments/assets/eb4e5cc5-32d1-45c8-b4eb-93ab7ecab41b" />

<img width="750" height="469" alt="Image" src="https://github.com/user-attachments/assets/4dea25c5-9515-4aa6-aee9-98dc106f06a5" />

**Comment by OrKoN** [comment]
Thanks for reporting! could you please try to restart Cursor? cc @sebastianbenz

**Comment by fahmi-pdso** [comment]
Possibly the same issue like https://github.com/ChromeDevTools/chrome-devtools-mcp/issues/92
Make sure you upgrade your nodejs to version 22. Happens to me too

If you want to see the specific error, you can see it on the output 

<img width="1190" height="418" alt="Image" src="https://github.com/user-attachments/assets/cabef3f3-380f-4d83-81db-68a93171525b" />

**Comment by OrKoN** [comment]
@emeagenciadigital could you please confirm that using Node 22+ solves the issue you are seeing?

**Comment by feldman22** [comment]
Hey! I'm facing the same issue and I'm using Node 22+ @OrKoN 

<img width="1316" height="692" alt="Image" src="https://github.com/user-attachments/assets/8e9ed70d-c6d6-459f-8e7f-74f2e8145ac1" />

**Comment by OrKoN** [comment]
@feldman22 the error says that `npx` does not exist. If Node 22+ is available to the client, `npx` is usually available as well. Could you check that the IDE is actually using Node 22+ and has npm/npx available?

**Comment by feldman22** [comment]
> [@feldman22](https://github.com/feldman22) the error says that `npx` does not exist. If Node 22+ is available to the client, `npx` is usually available as well. Could you check that the IDE is actually using Node 22+ and has npm/npx available?

Seems those were available, I tried restarting cursor but faced the same issue. Restarting my computer did the trick 😅. Thanks for the help! @OrKoN

**Comment by jacob-friis-akqa** [comment]
I experienced the same issue, and what helped me was to change the `command` and `args` properties to their relative paths:

```
    "chrome-devtools": {
      "command": "/opt/homebrew/opt/node@22/bin/node",
      "args": ["/opt/homebrew/lib/node_modules/chrome-devtools-mcp/build/src/index.js"]
    }
```

**Comment by tgig** [comment]
Same issue here, confirmed `Node.js v22.15.1`

Here's the output log for the MCP:
```
2025-09-24 11:52:22.498 [info] Handling CreateClient action
2025-09-24 11:52:22.498 [info] Starting new stdio process with command: npx chrome-devtools-mcp@latest
2025-09-24 11:52:22.498 [info] Handling ListOfferings action, server stored: false
2025-09-24 11:52:22.498 [error] No server info found
2025-09-24 11:52:23.472 [error] node:internal/modules/esm/resolve:275
    throw new ERR_MODULE_NOT_FOUND(
          ^

Error [ERR_MODULE_NOT_FOUND]: Cannot find module '/Users/travis/.npm/_npx/15c61037b1978c83/node_modules/zod-to-json-schema/dist/esm/index.js' imported from /Users/travis/.npm/_npx/15c61037b1978c83/node_modules/@modelcontextprotocol/sdk/dist/esm/server/mcp.js
    at finalizeResolution (node:internal/modules/esm/resolve:275:11)
    at moduleResolve (node:internal/modules/esm/resolve:860:10)
    at defaultResolve (node:internal/modules/esm/resolve:984:11)
    at ModuleLoader.defaultResolve (node:internal/modules/esm/loader:780:12)
    at #cachedDefaultResolve (node:internal/modules/esm/loader:704:25)
    at ModuleLoader.resolve (node:internal/modules/esm/loader:687:38)
    at ModuleLoader.getModuleJobForImport (node:internal/modules/esm/loader:305:38)
    at ModuleJob._link (node:internal/modules/esm/module_job:137:49) {
  code: 'ERR_MODULE_NOT_FOUND',
  url: 'file:///Users/travis/.npm/_npx/15c61037b1978c83/node_modules/zod-to-json-schema/dist/esm/index.js'
}

Node.js v22.15.1
```

**Comment by tgig** [comment]
> Same issue here, confirmed `Node.js v22.15.1`

Fixed by adding these args:
```
"chrome-devtools": {
      "command": "npx",
      "args": [
        "--yes",
        "--package", "chrome-devtools-mcp@latest",
        "--package", "zod-to-json-schema@3.22.3",
        "chrome-devtools-mcp",
        "--isolated=true",
        "--headless=false"
      ]
    }
```

**Comment by jvandyke** [comment]
For me, using ASDF, I used the environment variable to set the version. Replace with your own installed version >22.x.

```json
"chrome-devtools": {
  "command": "npx chrome-devtools-mcp@latest",
  "env": {
    "ASDF_NODEJS_VERSION": "24.7.0"
  },
  "args": []
},
```

And now:

<img width="639" height="414" alt="Image" src="https://github.com/user-attachments/assets/949cb1bc-f182-445f-8f2b-30bb3a4d76c0" />

**Comment by LeonardoSya** [comment]
I'm having the exact same issue as you, and I'm using a Mac Intel with Node.js v23.11.0. You can refer to this JSON configuration:

```
    "chrome-devtools": {
      "command": "bash",
      "args": [
        "-c",
        "export PATH=/Users/seiyazhang/.nvm/versions/node/v23.11.0/bin:$PATH && npx chrome-devtools-mcp@latest"
      ]
    }
```

This means that your computer may have multiple Node.js versions, and chrome-devtools-mcp is not sure which version of Node.js to use, so you need to specify it explicitly.
My service is currently running normally
<img width="589" height="845" alt="Image" src="https://github.com/user-attachments/assets/d1287843-2806-45b6-ad60-c3c8a8376809" />

**Comment by jackleeforce** [comment]
after upgrading Node to version 22.x, it work fine. thanks.

**Comment by m44rten1** [comment]
For me it worked using node 22, but I first needed to do this:
```
rm -rf ~/.npm/_npx
npm cache clean --force
```

**Comment by natorion** [comment]
This seems to be resolved, upgrading to the minimum node version makes it work. We are shipping an improvement that will make this problem more prominent in the future.

**Comment by jdnichollsc** [comment]
@natorion step by step process to fix this issue from Mac:
- Run the below commands to update NodeJS locally:
```sh
nvm install lts/jod
nvm use lts/jod
nvm alias default lts/jod
```
- Restart Cursor

**Comment by N-Demir** [comment]
> For me it worked using node 22, but I first needed to do this:
> 
> ```
> rm -rf ~/.npm/_npx
> npm cache clean --force
> ```

I was having this issue and this was the only thing that finally worked for me among all the suggestions on this repo!

**Comment by Wuntenn** [comment]
Cursor can fix it for you if you help it. I had the same output.

Inside cursor you can get the reasons why the mcp is failing by looking at the output logs and filtering for the chrome-devtools MCP. Take the output of this, cut and paste it into cursor and ask it to fix it and it will test and configure the fault.

You could fix it manually by looking at what the fault it and fixing the issue. Usually it will be because it can't find the command that you're using. This will be a case of re-shimming, or properly configuring the globals for that command so that it can be found by the mcp server.

This image shows the before and after logs for the MCP server:

<img width="1147" height="691" alt="Image" src="https://github.com/user-attachments/assets/c7c124ba-faf4-4267-b7b0-bf800aafbd05" />




This is the instruction I gave to cursor:
<img width="1234" height="900" alt="Image" src="https://github.com/user-attachments/assets/2f7acbca-1bcf-406f-b658-49a13af5be41" />

<img width="1225" height="500" alt="Image" src="https://github.com/user-attachments/assets/eee33dff-0c38-4283-90d2-04daab209700" />

Hope this helps someone!

**Comment by rluncasu** [comment]
My issue was this:
```
2025-10-13 16:26:28.952 [error] sh: /Users/raduluncasu/.npm/_npx/15c61037b1978c83/node_modules/.bin/chrome-devtools-mcp: Permission denied
```

solved with:
```
rm -rf ~/.npm/_npx
```

**Comment by nhatItsforce** [comment]
Hi all, it's related to node version. 
Even though we switched to the correct Node version using nvm, it still doesn’t work.
We need to set an absolute path for the npx command

on MacOS try

```
{
  "mcpServers": {
    "chrome-devtools": {
      "command": "/Users/adrian/.nvm/versions/node/v20.19.5/bin/npx",
      "args": [
        "-y",
        "chrome-devtools-mcp"
      ],
      "env": {
        "PATH": "/Users/adrian/.nvm/versions/node/v20.19.5/bin:${env:PATH}"
      }
    }
  }
}
```

It works with both VSCode and Cursor

**Comment by Knufle** [comment]
Just wanted to leave this here, if you're on Windows WSL like me and tried everything above without success, I just learned that for whatever reason, the `chromedevtools/chrome-devtools-mcp` uses Windows' node instead of whatever distro's WSL node you have, so in my case, I had node 22.20 on WSL but I also had node 22.11 on Windows itself, both setup using nvm and nvm for windows, so what I did was I updated node on Windows and now everything is working fine.

**Comment by admapop** [comment]
> For me, using ASDF, I used the environment variable to set the version. Replace with your own installed version >22.x.
> 
> "chrome-devtools": {
>   "command": "npx chrome-devtools-mcp@latest",
>   "env": {
>     "ASDF_NODEJS_VERSION": "24.7.0"
>   },
>   "args": []
> },
> And now:
> 
> <img alt="Image" width="639" height="414" src="https://private-user-images.githubusercontent.com/83712/493560527-949cb1bc-f182-445f-8f2b-30bb3a4d76c0.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3NjE2NjI3MDMsIm5iZiI6MTc2MTY2MjQwMywicGF0aCI6Ii84MzcxMi80OTM1NjA1MjctOTQ5Y2IxYmMtZjE4Mi00NDVmLThmMmItMzBiYjNhNGQ3NmMwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUxMDI4VDE0NDAwM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJhMWUwMWZmMTVjOWVjNDE5NGU2YTlhOTE5ODYyOTNmMjE4OTNkM2YxOGViOTVhZDJhYmY0OGYzNGU3Yjk1MWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.45WNeV36imC94Fjy-DWu7WOgHactvTLhg2odaHXDm7E">

This was it for me thanks!

**Comment by cheezmil** [comment]
"chrome-devtools": {
      "command": "pwsh",
      "args": [
        "-Command",
        "fnm use 24; npx chrome-devtools-mcp@latest"
      ]
    },

My fnm is set to 20 by default ,and using the MCP settings in the documentation will result in errors, while using nodejs24 will not. For example, this is a setting for Windows PowerShell7:

**Comment by seanxuu** [comment]
change your **mcp.json** to this:
```json
    "chrome-devtools": {
      "command": "/home/user/.cursor/bin/npx-wrapper.sh", 
      "args": ["-y", "chrome-devtools-mcp"]
    }
```
and this is **npx-wrapper.sh**
```bash
#!/bin/bash
# npx wrapper script that ensures nvm environment is loaded
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

# Get the current node version
NODE_VERSION=$(nvm version)
NODE_BIN_DIR="$NVM_DIR/versions/node/$NODE_VERSION/bin"

# Ensure node is in PATH (at the beginning)
export PATH="$NODE_BIN_DIR:$PATH"

# Execute npx with all arguments
exec "$NODE_BIN_DIR/npx" "$@"
```

**Comment by natorion** [comment]
Thanks. @sebastianbenz WDYT about adding the findings on this issue to our docs?

**Comment by Rabbitzzc** [comment]
```json
{
  "servers": {
    "chrome-devtools-mcp": {
      "command": "npx",
      "args": [
        "-y",
        "chrome-devtools-mcp@latest",
        "--browser-url=http://127.0.0.1:port"
      ],
      "env": {
        "HOME": "/Users/xxxx",
        "PATH": "/Users/xxx/.nvm/versions/node/v22.14.0/bin:/usr/local/bin:/usr/bin:/bin:/opt/homebrew/bin"
      }
    }
  }
}
```
